# Generated by Django 3.0.7 on 2020-06-16 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='included_topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=64, verbose_name='Topping')),
            ],
        ),
        migrations.CreateModel(
            name='item_in_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveSmallIntegerField(verbose_name='Quantity')),
                ('notes', models.TextField(verbose_name='Notes')),
                ('included_toppings', models.ManyToManyField(blank=True, related_name='toppings_included', to='orders.included_topping')),
                ('menu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.menu')),
            ],
        ),
        migrations.RenameModel(
            old_name='orders',
            new_name='order_placed',
        ),
        migrations.RenameModel(
            old_name='toppings',
            new_name='topping',
        ),
        migrations.DeleteModel(
            name='order_items',
        ),
        migrations.AddField(
            model_name='item_in_order',
            name='orders',
            field=models.ManyToManyField(related_name='items', to='orders.order_placed'),
        ),
        migrations.AddField(
            model_name='item_in_order',
            name='toppings',
            field=models.ManyToManyField(blank=True, related_name='toppings_added', to='orders.topping'),
        ),
    ]
